name: marifa-platform

services:
  postgres:
    image: postgres
    container_name: marifa-platform-postgres
    environment:
      POSTGRES_DB: marifa-platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - marifa-platform_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  marifa-platform_postgres_data: